### ISSUE TITLE
cannot import cuda_macros

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_menu#21]
При старте Куд-
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'cuda_macros'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'cuda_macros'
OK config menus from "/home/user/Downloads/kv-menu2.json"
```

**Comment by kvichans** [comment]
После какого изменения это появилось?
Чьи это сообщения?

**Comment by Alexey-T** [comment]
После удаления плагина Macros
его пункты есть в меню, есть п-т Macros-Activate

2- Сообщения ConfigMenu при старте Куд

**Comment by Alexey-T** [comment]
3- в вашем файле есть
```
    ]}
     ,{"cap":"&Macros", "hint":"_cuda_macros:adapt_menu"}
     ,{"cap":"&Plugins", "hint":"plugins"}
     ,{"cap":"&Tools", "hint":"_cuda_exttools:adapt_menu"}
```

**Comment by kvichans** [comment]
Ясно
Поправлю плаг
